spring.application.name=st-albatross-management-system
spring.data.mongodb.uri=mongodb+srv://sfajfer:Frozen21@st-albatross-management.eguy0au.mongodb.net/?appName=st-albatross-management-system
spring.mongodb.uri=mongodb+srv://sfajfer:Frozen21@st-albatross-management.eguy0au.mongodb.net/st-albatross-management?retryWrites=true&w=majority
server.port=9090